name: CI

on: [push, workflow_dispatch]

jobs: 

  build:

      runs-on: windows-latest

      steps: 

       -name: Download 

        run: Invoke-WebRequest
        https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip

        -name: Extract 
        
         run: Expand Achieve ngrok.zip 

        -name: Auth

        run: .\ngrok\ngrok.exe authtoken

     $Env:NGROK_AUTH_TOKEN

         env:

          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

         -name: Enable TS

          run: set-ItemProperty -Path
         'HKLM:\System\CurrentControlSet\Control\Terminal
         Server'-name"fDenyTSConnection"-Value 0

         -run: Enable-NetFirewallrule-DisplayGroup "Remote Desktop"

         -run:Set-ItemProperty -Path
         'HKML:\System\CurrentControlSet\Control\TerminalServer\Winstations\RDP-Tpc'-name"UserAuthentication" -Value 1

         -run: Set LocalUser -Name"smartpc" -Password (ConvertTo-SecureString -AsPlanText "edi@nalu"-Force)

         -name: Create Tunnel 

          run: .\ngrok\ngrok.exe tpc 3389
